import argparse
import collections
import csv
import math
from pathlib import Path

import numpy as np


def main() -> int:
    parser = argparse.ArgumentParser(description="Summarize per-site residuals.")
    parser.add_argument(
        "--residuals",
        default="runs/ceres-ground-test/fit_est_kappa/residuals.csv",
        help="Path to residuals.csv generated by fit_cli.",
    )
    args = parser.parse_args()

    fn = Path(args.residuals)
    sites = collections.defaultdict(list)
    with fn.open() as fh:
        r = csv.DictReader(fh)
        for row in r:
            site = (row.get("site") or "UNK").strip()
            res = math.hypot(float(row["res_ra_arcsec"]), float(row["res_dec_arcsec"]))
            sigma = float(row["sigma_arcsec"])
            sites[site].append((res, sigma))

    print("site  n_obs   median_res_arcsec  median_reported_sigma  ratio(med_res/sigma)")
    for s, vals in sorted(sites.items()):
        med_res = float(np.median([v[0] for v in vals]))
        med_sigma = float(np.median([v[1] for v in vals]))
        ratio = med_res / max(1e-12, med_sigma)
        print(f"{s:4s} {len(vals):5d} {med_res:18.3f} {med_sigma:22.3f} {ratio:17.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
